before_install:
  - gem install bundler
language: ruby
cache: bundler
rvm:
  - 2.3.1
  - 2.2.5
  - 2.1.10
  - ruby-head
  - jruby-head
env:
- COVERALLS=true
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
